# Generated by Django 4.0.2 on 2022-02-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='is_employee'),
        ),
        migrations.AlterField(
            model_name='createuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='is_staff'),
        ),
    ]
